routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('/test', "Client\HandBookController@getHandBookPaginate");
// Route::get('/test', function() {
//     return view('workwise.cv.candidate.find-employer');
// });

// Admin
Route::group([
    'namespace' => "Admin",
    'prefix' => 'admin',
], function () {
    Route::group([
        'middleware' => ['auth.admin', 'PreventBackHistory']
    ], function() {
        Route::get('/', 'DashboardController@index')->name('admin.home');
       

        Route::prefix('employer')->group(function () {
            Route::get('/', 'EmployerController@index')->name('admin.employer');
            Route::get('/updateStaus/{id}', "EmployerController@updateStatus")->name('admin.employer.updateStatus');
        });

        Route::get('/auth/logout', "Auth\LoginController@logout")->name('admin.logout');
        Route::prefix('handbook')->group(function () {
            Route::get('/', "HandBookController@index")->name('admin.handbook');
            Route::get('/create', "HandBookController@create")->name('handbook.create');
            Route::post('/store', "HandBookController@store")->name('handbook.store');
            Route::get('/edit/{id}', "HandBookController@edit");
            Route::post('/update/{id}', "HandBookController@update");
        });
    });

    Route::group([
        'namespace' => "Auth",
        'prefix' => 'auth',
    ], function() {
        Route::get('/login', "LoginController@formLogin");
        Route::post('/login', "LoginController@login")->name('admin.login');
    });
});

// Client
Route::group([
    'namespace' => "Client\Auth\Social",
    'prefix' => '/',
], function() {

    Route::get('login', 'LoginController@formLogin')->name('form-login');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/register', 'LoginController@register');
    Route::post('/forget-password', "LoginController@forgetPass")->name('forget-password');

    Route::prefix('auth')->group(function () {
        Route::get('/facebook', 'LoginController@redirectToFacebook')->name('redirect-to-facebook');
        Route::get('/facebook/callback', 'LoginController@handleFacebookCallback');

        Route::get('/google', 'LoginController@redirectToGoogle')->name('redirect-to-google');
        Route::get('/google/callback', 'LoginController@handleGoogleCallback');

        Route::get('/logout', 'LogoutController@logout')->name('logout');
    });
});

//Giao diện chính
// Không có đăng nhập
Route::get('/home', function() {
    return view('workwise.home.home');
})->name('home.page');
Route::get('/', "Client\JobController@index")->name('home');
Route::get('/job/detail/{id}', "Client\JobController@show")->name('job.detail');

//Hiển thị các comment của bài tin tuyển dụng
Route::get('/comment/show/{id}', "Client\CommentController@show");

//Chi tiết công ty tuyển dụng
Route::get('/company/show/{id}', "Client\CompanyController@show")->name('company.show');

// Cẩm nang
Route::get('/handbook', "Client\HandBookController@index")->name('handbook');
Route::get('/handbook-paginate', "Client\HandBookController@getHandBookPaginate");
Route::get('/handbook/{slug}', "Client\HandBookController@detail")->name('handbook.detail');
//Bắt buộc đăng nhập tài khoản
Route::group([
    'middleware' => ['auth','PreventBackHistory'],
],function () {
    Route::group([
        'namespace' => "Client"
    ], function() {
        //Giao diện mạng xã hội
        Route::get('/socail','DashboardController@index')->name('home.socail');

        // Phần bài viết của người dùng
        Route::prefix('post')->group(function () {
            Route::get('/show/{id}', "PostController@show");
            Route::post('/store', "PostController@store")->name('post.store');
            Route::post('/edit', "PostController@edit")->name('post.edit');
            Route::post('/update', "PostController@update")->name('post.update');
            Route::post('/destroy', "PostController@destroy")->name('post.destroy');
            Route::post('/like', "PostController@like");
            Route::post('/comment', "PostController@comment");
        });

        // Profile
        Route::prefix('profile')->group(function() {
            Route::get('/{id}', "UserController@profile")->name('user.profile');
            Route::post('/update-cover-image', "UserController@updateCoverImage")->name('user.update-cover-image');
            Route::post('/update-avatar', "UserController@updateAvatar")->name('user.update-avatar');
        });
        Route::prefix('setting-profile')->group(function() {
            Route::get('/{id}', "UserController@viewSettingProfile")->name('user.view-setting-profile');
            Route::post('/change-password/{id}', "UserController@changePassword")->name('user.setting-profile.change-password');
            Route::post('/update', "UserController@update")->name('user.update');
        });
        Route::get('/user/update-status-cv', "UserController@updateStatus");

        // Công ty tuyển dụng
        Route::prefix('company')->group(function () {
            Route::post('/update', "CompanyController@update");
            Route::post('/update-image', "CompanyController@updateImage");
        });

        //Bải tin tuyển dụng
        Route::group([
            'middleware' => ['checkRole'],
        ], function () {
            Route::prefix('job')->group(function () {
                Route::get('/create', "JobController@create")->name('job.create');
                Route::post('/store', "JobController@store")->name('job.store');
                Route::get('/list', "JobController@list")->name('job.list');
                Route::get('/edit/{id}', "JobController@edit")->name('job.edit');
                Route::post('/update', "JobController@update")->name('job.update');
                Route::post('/destroy/{id}', "JobController@destroy")->name('job.destroy');
                Route::get('/update-status/{id}', "JobController@updateStatus")->name('job.update-status');
            });
        });
        // Chức năng like bài tin
        Route::post('job/like', "JobController@like");

        // Bình luận bài tin
        Route::prefix('comment')->group(function () {
            Route::post('/store', "CommentController@store");
            Route::post('/destroy', "CommentController@destroy");
            
        });

        Route::prefix('chat')->group(function () {
            Route::get('/user/{id}', "ChatController@index")->name('chat.index');
            Route::post('/message', "ChatController@store");
            Route::get('/search', "ChatController@search");
        });

        //CV
        Route::prefix('cv')->group(function () {
            Route::get('/', "CvController@index")->name('cv.index');
            Route::post('/upload', "CvController@store")->name('cv.store');
            Route::post('/upload-main-cv', "CvController@updateMainCv");
            Route::post('/apply-job', "CvController@apply");
            Route::get('/cv-apply', "CvController@uiCvApply")->name('cv.ui-apply');
            Route::post('/find-job', "CvController@findJob");
            

            Route::middleware(['checkRole'])->group(function () {
                Route::get('/manage-cv', "CvController@uiManageCv")->name('cv.manage');
                
                //Giao diện xem danh sách hồ sơ các ứng viên đã lưu
                Route::get('/manage-save-cv', "CvController@uiSaveCv")->name('cv.manage-save-cv');

                //Xem danh sách ứng viên ứng tuyển
                Route::post('/view-candidate', "CvController@viewCandidate");

                //Tìm kiếm ứng viên
                Route::get('/find-candidate', "CvController@findCandidate")->name('cv.find-candidate');

                //Lưu cv ứng viên
                Route::get('/save-cv/{id}', "CvController@saveCv")->name('cv.save');

                Route::post('/update-cv-candidate', "CvController@updateCvCandidate");
            });
        });
            
    });

    //Đăng xuất tài khoản
    // Route::get('/logout','LoginController@logout');
});

app/Models/HandBook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Storage;

class HandBook extends Model
{
    use HasFactory;

    public function getImageUrlAttribute() {
        return Storage::url($this->thumbnail);
    }
}

app/Http/Controllers/Admin/HandBookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\HandBookService;
use App\Models\HandBook;

class HandBookController extends Controller
{
    private $handbook;
    public function __construct(HandBookService $handbookService) {
        $this->handbook = $handbookService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->handbook->index();

        return view('admin.handbook.index', [
            'posts' => $posts,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.handbook.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->handbook->store($request);
        
        return redirect()->route('admin.handbook');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/HandBookController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\HandBookService;
use App\Traits\ResponseTrait;
use App\Models\HandBook;

class HandBookController extends Controller
{
    use ResponseTrait;

    private $handbook;
    public function __construct(HandBookService $handbookService) {
        $this->handbook = $handbookService;
    }
    public function index() {
        $handbooksHot = $this->handbook->getIsHotHandBook();
        return view('workwise.handbook.index', [
            'handbooksHot' => $handbooksHot,
        ]);
    }

    public function detail($slug) {
        $data = $this->handbook->detail($slug);
       
        return view('workwise.handbook.detail', [
            'data' => $data,
        ]);
    }

    public function getHandBookPaginate() {
        $handbooks = $this->handbook->getHandBookPaginate();

        return $this->responseSuccess($handbooks);
    }
}

resources/views/admin/handbook/create.blade.php
@extends('admin.layouts.master')

@section('main-content')
    <main id="content" role="main" class="main">
        <!-- Content -->
        <form action="{{ route('handbook.store') }}" method="POST" id="formCreateHandBook" enctype="multipart/form-data">
            @csrf
            <div class="content container-fluid">
                <div class="page-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h1 class="page-header-title">Tạo mới cẩm nang</h1>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-5 col-12">
                        <h4>Ảnh</h4>
                        <div class="wrapper-img d-flex justify-content-center align-items-center position-relative" id="wrapper-ipt">
                            <div class="wrapper-icon">
                                <i class="bi bi-plus-lg"></i>
                            </div>
                            <input type="file" class="d-none" id="ipt-file" name="file">
                            <div class="wrapper-img__action">
                                <i class="bi bi-arrow-bar-up text-white me-2 action--upload"></i>
                                <i class="bi bi-trash3 action--delete"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-7 col-12">
                        <div class="mb-4">
                            <label for="" class="fw-bold mb-2">Tiêu đề</label>
                            <input type="text" id="title" class="form-control" name="title" placeholder="Tiêu đề cẩm nang .....">
                            <span class="text-error">Tiêu đề không được bỏ trống.</span>
                        </div>
                        <div class="mb-4">
                            <label for="" class="fw-bold mb-2">Mô tả</label>
                            <textarea name="description" id="" cols="30" rows="10"  class="form-control"></textarea>
                        </div>
                        <div class="mb-4">
                            <input type="checkbox" name="is_hot" class="form-check-input" />
                            <span>Nổi bật</span>
                        </div>
                        <div class="mb-4">
                            <label for="" class="fw-bold">Trạng thái</label>
                            <div class="bg-input-switches mt-2">
                                <input type="checkbox" name="status" class="w-100 h-100 ip-status" checked>
                                <span class="circle"></span>
                                <span class="bg-switches"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <label for="" class="fw-bold my-2 w-100 d-flex align-items-center justify-content-between">Nội dung
                            <span class="text-error m-0 fw-normal">Nội dung không được bỏ trống.</span>
                        </label>
                        <textarea name="content" id="content_handbook" rows="10" cols="80"></textarea>
                    </div>
                    <div class="col-12 d-flex justify-content-end">
                        <button id="btn-submit-frm" class="btn btn-primary">Tạo mới</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- Footer -->
        <div class="footer">
            <div class="row justify-content-between align-items-center">
                <div class="col">
                    <p class="fs-6 mb-0">&copy; WorkWise <span class="d-none d-sm-inline-block">2023
                            DNDev.</span></p>
                </div>
                <!-- End Col -->
            </div>
            <!-- End Row -->
        </div>

        <!-- End Footer -->

        <div id="liveToast" class="position-fixed toast hide" role="alert" aria-live="assertive" aria-atomic="true" style="top: 20px; right: 20px; z-index: 1000;" data-bs-delay="2000">
            <div class="toast-header">
              <div class="d-flex align-items-center">
                <div class="">
                  <h5 class="mb-0 d-flex align-items-center"> <span class="icon-error-toastr me-2"><i class="bi bi-x"></i></span> Lỗi</h5>
                </div>
              </div>
            </div>
            <div class="toast-body">
              
            </div>
          </div>
    </main>
@endsection
@section('script')
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('content_handbook');
            const liveToast = new bootstrap.Toast(document.querySelector('#liveToast'));
            var boolen = true;

            $('#wrapper-ipt').on('click', () => {
                if(boolen) {
                    clickIpt();
                }
            });
            
            $('#ipt-file').on('change', function(e) {
                let file = e.target.files[0];
                let type = file.type;
                let size = file.size;

                if(type.split("/")[0] !== "image") {
                    showToastr("Ảnh không đúng định dạng.");
                    return false;
                }
                if(size > 1000141) {
                    showToastr("Kích thước ảnh phải nhỏ hơn 1MB.");
                    return false;
                }
                let reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onloadend = () => {
                    let image = new Image();
                    image.src = reader.result
                    image.className   = "wrapper-img__src";
                    $('.wrapper-img').children('img').remove()
                    $('.wrapper-img').addClass('wrapper-img-active').prepend(image);
                    boolen = false;
                }
            });

            $('.action--upload').on('click', function() {
                $('#ipt-file')[0].click();
            });

            $('.action--delete').on('click', function() {
                $('#wrapper-img__src').removeAttr('src');
                $('.wrapper-img').removeClass('wrapper-img-active').children('img').remove();
                $('#ipt-file').val('');
                setTimeout(() => {
                    boolen = true;
                }, 1000);
            });

            $("#btn-submit-frm").on('click', function(e) {
                e.preventDefault();
               
                if(isValid()) {
                    $('#formCreateHandBook').submit();
                }
            });

            function showToastr(text) {
                $('.toast-body').text(text);
                liveToast.show();
            }

            function clickIpt() {
                $('#ipt-file')[0].click();
            }

            function isValid() {
                let title = $('#title');
                let content = CKEDITOR.instances.content_handbook.getData().length;
                let error = $('.text-error');


                if(title.val() == "" || title.length == 0) {
                    error.eq(0).css('display','inline-block');
                    return false;
                }

                if(content == 0) {
                    error.eq(1).css('display','inline-block');
                    return false;
                }

                return true;
            }

            $('#title').on('keyup', function() {
                $('.text-error').eq(0).css('display','none');
            });
            CKEDITOR.instances.content_handbook.on( 'key', function( evt ){
                $('.text-error').eq(1).css('display','none');
            });
        });
    </script>
@endsection

resources/views/admin/handbook/index.blade.php
@extends('admin.layouts.master')

@section('main-content')
    <main id="content" role="main" class="main">
        <!-- Content -->
        <div class="content container-fluid">
            <!-- Page Header -->
            <div class="page-header">
                <div class="row align-items-center">
                    <div class="col">
                        <h1 class="page-header-title">Cẩm nang</h1>
                    </div>
                    <!-- End Col -->
                </div>
                <!-- End Row -->
            </div>
            <!-- End Page Header -->
            <div class="d-flex justify-content-end mb-3">
                <a href="{{ route('handbook.create') }}" class="btn btn-primary"><i class="bi bi-plus"></i> Tạo mới</a>
            </div>
            <!-- Card -->
            <div class="card mb-3 mb-lg-5">
                <!-- Header -->
                <div class="card-header">
                    <div class="row justify-content-between align-items-center flex-grow-1">
                        <div class="col-md">
                            <div class="d-flex justify-content-between align-items-center">
                                <h4 class="card-header-title">Danh sách bài viết</h4>
                            </div>
                        </div>
                        <!-- End Col -->
                        <div class="col-auto">
                            <!-- Filter -->
                            <div class="row align-items-sm-center">
                                <div class="col-md">
                                    <form>
                                        <!-- Search -->
                                        <div class="input-group input-group-merge input-group-flush">
                                            <div class="input-group-prepend input-group-text">
                                                <i class="bi-search"></i>
                                            </div>
                                            <input id="datatableSearch" type="search" class="form-control"
                                                placeholder="Nhập để tìm kiếm" aria-label="Search users">
                                        </div>
                                        <!-- End Search -->
                                    </form>
                                </div>
                                <!-- End Col -->
                            </div>
                            <!-- End Filter -->
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Row -->
                </div>
                <!-- End Header -->

                <!-- Table -->
                <div class="table-responsive datatable-custom">
                    <table id="datatable"
                        class="table table-borderless table-thead-bordered table-nowrap table-align-middle card-table"
                        data-hs-datatables-options='{
                        "columnDefs": [{
                            "targets": [0, 1, 2, 3, 4],
                            "orderable": false
                            }],
                        "order": [],
                        "info": {
                            "totalQty": "#datatableWithPaginationInfoTotalQty"
                        },
                        "search": "#datatableSearch",
                        "entries": "#datatableEntries",
                        "pageLength": 10,
                        "isResponsive": false,
                        "isShowPaging": false,
                        "pagination": "datatablePagination"
                        }'>
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="table-column-pe-0">
                                   #
                                </th>
                                <th>Ảnh</th>
                                <th>Tiêu đề</th>
                                <th>Trạng thái</th>
                                <th class="text-center">Hành động</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($posts as $index => $post)
                                <tr>
                                    <td class="table-column-pe-0">{{ ++$index }}</td>
                                    <td class="table-column-ps-0 text-center">
                                        <a class="d-flex align-items-center justify-content-center" href="#">
                                            <div class="flex-shrink-0">
                                                <div class="avatar avatar-sm">
                                                    <img class="avatar-img ratio ratio-1x1" src="{{ $post->image_url }}"
                                                        alt="Image Description">
                                                </div>
                                            </div>
                                        </a>
                                    </td>
                                    <td class="text-truncate text-wrap">
                                        {{ $post->title }} <br>
                                        @if($post->is_hot == 1)
                                            <span class="text-danger px-1 py-1" style="font-size: 12px; border:1px solid red">Nổi bật</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if($post->status == 1) 
                                            <span class="legend-indicator bg-success"></span>Hiển thị
                                        @else
                                            <span class="legend-indicator bg-danger"></span>Ẩn
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="" class="text-primary me-2" data-bs-toggle="tooltip" title="Cập nhật">
                                            <i class="bi bi-pencil-square"></i>
                                        </a>
                                        <a href="" class="text-danger" data-bs-toggle="tooltip" title="Xóa">
                                            <i class="bi bi-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- End Table -->

                <!-- Footer -->
                <div class="card-footer">
                    <!-- Pagination -->
                    <div class="row justify-content-center justify-content-sm-between align-items-sm-center">
                        <div class="col-sm mb-2 mb-sm-0">
                            <div class="d-flex justify-content-center justify-content-sm-start align-items-center">
                                <span class="me-2">Hiển thị:</span>

                                <!-- Select -->
                                <div class="tom-select-custom">
                                    <select id="datatableEntries"
                                        class="js-select form-select form-select-borderless w-auto" autocomplete="off"
                                        data-hs-tom-select-options='{
                                        "searchInDropdown": false,
                                        "hideSearch": true
                                    }'>
                                        <option value="1" selected>1 bản ghi</option>
                                        <option value="6">6 bản ghi</option>
                                        <option value="8" >8 bản ghi</option>
                                        <option value="12">12 bản ghi</option>
                                    </select>
                                </div>
                                <!-- End Select -->

                                <span class="text-secondary me-2">của</span>

                                <!-- Pagination Quantity -->
                                <span id="datatableWithPaginationInfoTotalQty"></span>
                            </div>
                        </div>
                        <!-- End Col -->

                        <div class="col-sm-auto">
                            <div class="d-flex justify-content-center justify-content-sm-end">
                                <!-- Pagination -->
                                <nav id="datatablePagination" aria-label="Activity pagination"></nav>
                            </div>
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Pagination -->
                </div>
                <!-- End Footer -->
            </div>
            <!-- End Card -->
        </div>
        <!-- End Content -->

        <!-- Footer -->

        <div class="footer">
            <div class="row justify-content-between align-items-center">
                <div class="col">
                    <p class="fs-6 mb-0">&copy; WorkWise <span class="d-none d-sm-inline-block">2023
                            DNDev.</span></p>
                </div>
                <!-- End Col -->
            </div>
            <!-- End Row -->
        </div>

        <!-- End Footer -->
    </main>
@endsection