routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::get('/test', "Client\HandBookController@getHandBookPaginate");
// Route::get('/test', function() {
//     return view('workwise.cv.candidate.find-employer');
// });

// Admin
Route::group([
    'namespace' => "Admin",
    'prefix' => 'admin',
], function () {
    Route::group([
        'middleware' => ['auth.admin', 'PreventBackHistory']
    ], function() {
        Route::get('/', 'DashboardController@index')->name('admin.home');
       

        Route::prefix('employer')->group(function () {
            Route::get('/', 'EmployerController@index')->name('admin.employer');
            Route::get('/updateStaus/{id}', "EmployerController@updateStatus")->name('admin.employer.updateStatus');
        });

        Route::get('/auth/logout', "Auth\LoginController@logout")->name('admin.logout');
        Route::prefix('handbook')->group(function () {
            Route::get('/', "HandBookController@index")->name('admin.handbook');
            Route::get('/create', "HandBookController@create")->name('handbook.create');
            Route::post('/store', "HandBookController@store")->name('handbook.store');
            Route::get('/edit/{id}', "HandBookController@edit");
            Route::post('/update/{id}', "HandBookController@update");
        });
    });

    Route::group([
        'namespace' => "Auth",
        'prefix' => 'auth',
    ], function() {
        Route::get('/login', "LoginController@formLogin");
        Route::post('/login', "LoginController@login")->name('admin.login');
    });
});

// Client
Route::group([
    'namespace' => "Client\Auth\Social",
    'prefix' => '/',
], function() {

    Route::get('login', 'LoginController@formLogin')->name('form-login');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/register', 'LoginController@register');
    Route::post('/forget-password', "LoginController@forgetPass")->name('forget-password');

    Route::prefix('auth')->group(function () {
        Route::get('/facebook', 'LoginController@redirectToFacebook')->name('redirect-to-facebook');
        Route::get('/facebook/callback', 'LoginController@handleFacebookCallback');

        Route::get('/google', 'LoginController@redirectToGoogle')->name('redirect-to-google');
        Route::get('/google/callback', 'LoginController@handleGoogleCallback');

        Route::get('/logout', 'LogoutController@logout')->name('logout');
    });
});

//Giao diện chính
// Không có đăng nhập
Route::get('/home', function() {
    return view('workwise.home.home');
})->name('home.page');
Route::get('/', "Client\JobController@index")->name('home');
Route::get('/job/detail/{id}', "Client\JobController@show")->name('job.detail');

//Hiển thị các comment của bài tin tuyển dụng
Route::get('/comment/show/{id}', "Client\CommentController@show");

//Chi tiết công ty tuyển dụng
Route::get('/company/show/{id}', "Client\CompanyController@show")->name('company.show');

// Cẩm nang
Route::get('/handbook', "Client\HandBookController@index")->name('handbook');
Route::get('/handbook-paginate', "Client\HandBookController@getHandBookPaginate");
Route::get('/handbook/{slug}', "Client\HandBookController@detail")->name('handbook.detail');
//Bắt buộc đăng nhập tài khoản
Route::group([
    'middleware' => ['auth','PreventBackHistory'],
],function () {
    Route::group([
        'namespace' => "Client"
    ], function() {
        //Giao diện mạng xã hội
        Route::get('/socail','DashboardController@index')->name('home.socail');

        // Phần bài viết của người dùng
        Route::prefix('post')->group(function () {
            Route::get('/show/{id}', "PostController@show");
            Route::post('/store', "PostController@store")->name('post.store');
            Route::post('/edit', "PostController@edit")->name('post.edit');
            Route::post('/update', "PostController@update")->name('post.update');
            Route::post('/destroy', "PostController@destroy")->name('post.destroy');
            Route::post('/like', "PostController@like");
            Route::post('/comment', "PostController@comment");
        });

        // Profile
        Route::prefix('profile')->group(function() {
            Route::get('/{id}', "UserController@profile")->name('user.profile');
            Route::post('/update-cover-image', "UserController@updateCoverImage")->name('user.update-cover-image');
            Route::post('/update-avatar', "UserController@updateAvatar")->name('user.update-avatar');
        });
        Route::prefix('setting-profile')->group(function() {
            Route::get('/{id}', "UserController@viewSettingProfile")->name('user.view-setting-profile');
            Route::post('/change-password/{id}', "UserController@changePassword")->name('user.setting-profile.change-password');
            Route::post('/update', "UserController@update")->name('user.update');
        });
        Route::get('/user/update-status-cv', "UserController@updateStatus");

        // Công ty tuyển dụng
        Route::prefix('company')->group(function () {
            Route::post('/update', "CompanyController@update");
            Route::post('/update-image', "CompanyController@updateImage");
        });

        //Bải tin tuyển dụng
        Route::group([
            'middleware' => ['checkRole'],
        ], function () {
            Route::prefix('job')->group(function () {
                Route::get('/create', "JobController@create")->name('job.create');
                Route::post('/store', "JobController@store")->name('job.store');
                Route::get('/list', "JobController@list")->name('job.list');
                Route::get('/edit/{id}', "JobController@edit")->name('job.edit');
                Route::post('/update', "JobController@update")->name('job.update');
                Route::post('/destroy/{id}', "JobController@destroy")->name('job.destroy');
                Route::get('/update-status/{id}', "JobController@updateStatus")->name('job.update-status');
            });
        });
        // Chức năng like bài tin
        Route::post('job/like', "JobController@like");

        // Bình luận bài tin
        Route::prefix('comment')->group(function () {
            Route::post('/store', "CommentController@store");
            Route::post('/destroy', "CommentController@destroy");
            
        });

        Route::prefix('chat')->group(function () {
            Route::get('/user/{id}', "ChatController@index")->name('chat.index');
            Route::post('/message', "ChatController@store");
            Route::get('/search', "ChatController@search");
        });

        //CV
        Route::prefix('cv')->group(function () {
            Route::get('/', "CvController@index")->name('cv.index');
            Route::post('/upload', "CvController@store")->name('cv.store');
            Route::post('/upload-main-cv', "CvController@updateMainCv");
            Route::post('/apply-job', "CvController@apply");
            Route::get('/cv-apply', "CvController@uiCvApply")->name('cv.ui-apply');
            Route::post('/find-job', "CvController@findJob");
            

            Route::middleware(['checkRole'])->group(function () {
                Route::get('/manage-cv', "CvController@uiManageCv")->name('cv.manage');
                
                //Giao diện xem danh sách hồ sơ các ứng viên đã lưu
                Route::get('/manage-save-cv', "CvController@uiSaveCv")->name('cv.manage-save-cv');

                //Xem danh sách ứng viên ứng tuyển
                Route::post('/view-candidate', "CvController@viewCandidate");

                //Tìm kiếm ứng viên
                Route::get('/find-candidate', "CvController@findCandidate")->name('cv.find-candidate');

                //Lưu cv ứng viên
                Route::get('/save-cv/{id}', "CvController@saveCv")->name('cv.save');

                Route::post('/update-cv-candidate', "CvController@updateCvCandidate");
            });
        });
            
    });

    //Đăng xuất tài khoản
    // Route::get('/logout','LoginController@logout');
});

app/Models/FindJob.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FindJob extends Model
{
    use HasFactory;

    public function getJsonJobAttribute() {
        return json_decode($this->jobs, true);
    }

    public function getJsonAddressAttribute() {
        return json_decode($this->address, true);
    }
}

app/Http/Controllers/Admin/EmployerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\CompanyService;

class EmployerController extends Controller
{
    private $company;
    public function __construct(CompanyService $companyService) {
        $this->company = $companyService;
    }

    public function index() {
        $companies = $this->company->index();

        return view('admin.employer.index', [
            'companies' => $companies,
        ]);
    }

    public function updateStatus($id) {
        $this->company->updateStatus($id);

        return back();
    }
}

resources/views/workwise/cv/employer/find-candidate.blade.php
@extends('workwise.layouts.master')

@section('style')
    <link rel="stylesheet" href="/workwise/css/work/style.css">
@endsection

@section('main-content')
    <form method="GET" id="formSubmitSearch">
        <main>
            <div class="main-section">
                <div class="container">
                    <div class="main-section-data">
                        <div class="row">
                            <div class="col-lg-12">
                                <h3 class="title-jobsss">
                                    <img src="/workwise/images/icons/exp_ntv_mnhat.png" alt="" class="mr-2">
                                    Danh sách ứng viên
                                </h3>
                                <div class="main-ws-sec mb-5">
                                    <div class="list-candidate d-flex flex-column">
                                        @foreach ($candidates as $candidate)
                                            @if ($candidate->findJob && $candidate->status_cv == 1)
                                                <div class="info-candidate d-flex my-3 bg-white px-3 py-2">
                                                    <div class="avatar-candidate">
                                                        <img src="{{ $candidate->userInfo->CheckEmptyImage() }}"
                                                            alt="" width="95" height="95"
                                                            style="border-radius:50%; object-fit:cover">
                                                    </div>
                                                    <div class="ml-3">
                                                        <div class="d-flex">
                                                            @foreach ($candidate->findJob->json_job as $job)
                                                                <h2 style="font-weight:bold" class="mr-1">
                                                                    {{ $job }},
                                                                </h2>
                                                            @endforeach
                                                        </div>

                                                        <h2 style="color: #F88C00; font-size:16px" class="mt-3">{{ $candidate->name }}</h2>

                                                        <div class="d-flex mt-3">
                                                            <div>
                                                                <img src="/workwise/images/icons/dt_7.png" alt="" class="mr-1"> {{ $user->userInfo->address ?? 'Đang cập nhật' }}
                                                            </div>
                                                            <div class="ml-5">
                                                                <img src="/workwise/images/icons/dt_6.png" alt="" class="mr-1"> Chi tiết trong CV
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex flex-column justify-content-center ml-auto">
                                                        <a href="{{ route('chat.index', $candidate->id) }}" target="_blank" style="background: #5DC22D !important; color: white; padding: 7px; border-radius: 20px;" class="d-flex align-items-end justify-content-center">
                                                            <i class="fa fa-weixin mr-1" aria-hidden="true"></i> Chat
                                                        </a>
                                                        <a href="" style="color: #4C5BD4; border:0.8px solid #4C5BD4; padding: 7px; border-radius: 20px;" 
                                                                        class="btn-save-cv mt-2 d-flex align-items-end justify-content-center"
                                                                        data-id="{{ $candidate->id }}">
                                                            <i class="fa fa-floppy-o mr-1" aria-hidden="true"></i> Lưu
                                                        </a>
                                                    </div>
                                                </div>
                                            @endif
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </form>
@endsection

@section('script')
    <script>
            $(document).ready(function () {
                $(".btn-save-cv").on('click', function(e) {

                    let id = $(this).data('id');
                    
                    e.preventDefault();
                    
                    $.ajax({
                        type: "GET",
                        url: "/cv/save-cv/"+ id,
                        dataType: "JSON",
                        success: function (response) {
                            if(response.code == 1) {
                                toastr.info(response.message);
                            }else if(response.code == 0) {
                                toastr.success("Lưu ứng viên thành công");
                            }
                        }
                    });
                })
            });
    </script>
@endsection

resources/views/workwise/cv/employer/index.blade.php
@extends('workwise.layouts.master')

@section('style')
    <link rel="stylesheet" href="/workwise/css/work/list.css">
@endsection

@section('main-content')
    <section class="profile-account-setting">
        <div class="container-fluid">
            <div class="account-tabs-setting">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="tab-content" id="nav-tabContent">

                            <div class="tab-pane active show" id="nav-notification" role="tabpanel"
                                aria-labelledby="nav-notification-tab">
                                <div class="acc-setting">
                                    <h3>Trang chủ &nbsp; &rarr; &nbsp; Quản lí công việc tuyển dụng </h3>
                                </div>

                                <div class="mt-5">
                                    <div class="notfication-details p-0 mt-5">
                                        <table class="table">
                                            <thead class="thead-dark">
                                                <tr>
                                                    <th scope="col" class="text-center">STT</th>
                                                    <th scope="col" class="text-center">Vị trí tuyển dụng</th>
                                                    <th scope="col" class="text-center">Số ứng tuyển</th>
                                                    <th scope="col" class="text-center">Hành động</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (count($jobs) > 0)
                                                    @foreach ($jobs as $index => $job)
                                                        <tr>
                                                            <td class="text-center"> {{ ++$index }} </td>
                                                            <td class="text-center"> {{ $job->title }} </td>
                                                            <td class="text-center"> {{ count($job->users) }} </td>
                                                            <td class="text-center">
                                                                <button class="btn btn-success btn-view-candidate"
                                                                    data-toggle="modal" data-target="#exampleModalCenter"
                                                                    data-id="{{ $job->id }}">
                                                                    Xem danh sách
                                                                </button>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                @else
                                                    <tr>
                                                        <td colspan="4" class="text-center p-5">Không có dữ liệu....</td>
                                                    </tr>
                                                @endif
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
            <div class="modal-content">
                <div class="header d-flex flex-column align-items-center py-3">
                    <h1 class="header_title-modal mb-2">Danh sách ứng viên</h1>
                    <p class="header_name-work">Công việc: <span class="name-work"></span></p>
                </div>
                <div class="middle-modal px-3">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" class="text-center">STT</th>
                                <th scope="col" class="text-center">Vị trí tuyển dụng</th>
                                <th scope="col" class="text-center">Tên ứng viên</th>
                                <th scope="col" class="text-center">Ngày nộp</th>
                                <th scope="col" class="text-center">Hành động</th>
                                <th scope="col" class="text-center">Kết quả</th>
                            </tr>
                        </thead>
                        <tbody class="list-candidate">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {{-- Modal đặt lịch hẹn phỏng vấn --}}
    <div class="modal fade" id="ModalSetTime" tabindex="-1" role="dialog" aria-labelledby="ModalSetTimeTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="header d-flex flex-column align-items-center py-3">
                    <h1 class="header_title-modal mb-2">Cập nhật thời gian hẹn phỏng vấn</h1>
                </div>
                <div class="middle-modal px-3" style="height: 150px">
                    <input type="datetime-local" class="form-control" id="time-interview">
                    <div class="mt-3 fl-right">
                        <button class="btn btn-primary" onclick="handleSetTimeInterview()">Cập nhật</button>
                        <button class="btn btn-danger" id="close-modal-set-time" data-dismiss="modal">Hủy bỏ</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        var _token = $('meta[name="csrf-token"]').attr('content');
        var dataAjax = {
            status: '',
            jobId: '',
            userId: '',
            valueStatus: '',
            text: '',
        }

        $(document).ready(function() {
            $('.btn-view-candidate').on('click', function() {
                let id = $(this).data('id');

                $.ajax({
                    type: "POST",
                    url: "/cv/view-candidate",
                    data: {
                        _token,
                        id,
                    },
                    dataType: "JSON",
                    success: function(response) {
                        $('.name-work').text(response.data.title);
                        $('.list-candidate').empty();
                        $.each(response.data.users, function(index, value) {
                            let time_interview = '';
                            if (value.time_interview != null) {
                                let date = new Date(value.time_interview);
                                let hour = date.getHours();
                                let minute = date.getMinutes();
                                let day = date.getDate();
                                let month = date.getMonth() + 1;
                                let year = date.getFullYear();

                                time_interview = "(" + hour + ":" + minute + " ngày " +
                                    day + "/" + month + "/" + year + ")";
                            }
                            $('.list-candidate').append(
                                `<tr>
                                    <td class="text-center">${++index}</td>
                                    <td class="text-center">${response.data.title}</td>
                                    <td class="text-center">${value.name}</td>
                                    <td class="text-center">${value.date_format}</td>
                                    <td class="text-center">
                                        <a href="${value.cv}" class="btn btn-primary" target="_blank">Xem CV</a>
                                    </td>
                                    <td class="text-center hover-menu position-relative ">
                                        <span class="text-menu-status">
                                            ${value.status_apply}
                                        </span>
                                        <div class="position-absolute menu-status">
                                                @foreach (App\Models\MyCv::$status_text as $indexStaus => $valueStatus)
                                                    <a class="status-item status-item-action" data-current="${value.status_value}" data-job="${response.data.id}" data-user="${value.id}" data-value="{{ $indexStaus }}">{{ $valueStatus }}</a>
                                                @endforeach
                                        </div>
                                        <p class="time-await-interview">
                                            ${time_interview}
                                        </p>
                                    </td>
                                </tr>`
                            )
                        });
                        handleSetDisable()
                    }
                });
            });

            $(document).on('click', '.status-item-action', function() {
                let status = $(this);
                let jobId = $(this).data('job');
                let userId = $(this).data('user');
                let valueStatus = $(this).data('value');
                let text = $(this).text();

                if (valueStatus == 1) {
                    dataAjax = {
                        status: status,
                        jobId,
                        userId,
                        valueStatus,
                        text,
                    }
                    return false;
                }
                callAjaxUpdateCv(status, jobId, userId, valueStatus, text);
            });
        });

        function handleSetDisable() {
            for (let i = 0; i < $('.status-item').length; i++) {
                if ($('.status-item').eq(i).data('current') === $('.status-item').eq(i).data('value')) {
                    $('.status-item').eq(i).addClass('status-item-choose');
                }
                if ($('.status-item').eq(i).data('value') <= $('.status-item').eq(i).data('current')) {
                    $('.status-item').eq(i).addClass('status-item-disable');
                    $('.status-item').eq(i).removeClass('status-item-action');
                }
                if ($('.status-item').eq(i).data('value') == 1 && $('.status-item').eq(i).hasClass('status-item-action')) {
                    $('.status-item').eq(i).attr({
                        'data-toggle': 'modal',
                        'data-target': '#ModalSetTime'
                    })
                }
            }
        }

        function handleSetTimeInterview() {
            let time = $('#time-interview').val();
            if (time == '') {
                alert("Vui lòng chọn thời gian phỏng vấn ứng viên.");
                return false;
            } else {
                callAjaxUpdateCv(dataAjax.status, dataAjax.jobId, dataAjax.userId, dataAjax.valueStatus, dataAjax.text,
                    time);
                let date = new Date(time);
                let hour = date.getHours();
                let minute = date.getMinutes();
                let day = date.getDate();
                let month = date.getMonth() + 1;
                let year = date.getFullYear();

                dataAjax.status.parents('.hover-menu').append(
                    `<p class="time-await-interview">
                        ( ${hour}:${minute} ngày ${day}/${month}/${year} )
                    </p>`
                )
                $('#close-modal-set-time').click();
            }
        }

        function callAjaxUpdateCv(status, jobId, userId, valueStatus, text, time = null) {
            $.ajax({
                type: "POST",
                url: "/cv/update-cv-candidate",
                data: {
                    _token,
                    jobId,
                    userId,
                    valueStatus,
                    time,
                },
                dataType: "JSON",
                success: function(response) {
                    status.parent().siblings('.text-menu-status').text(text);
                    status.removeClass('status-item-action').prevAll().removeClass('status-item-action');
                    status.addClass('status-item-choose').prevAll().removeClass('status-item-choose').addClass(
                        'status-item-disable');
                    toastr.success("Cập nhật thành công.");
                }
            });
        }
    </script>
@endsection

{{-- 
<p>(Lịch hẹn Ngày 12-10-2001)</p> --}}